#pragma once

// Umbrella header: pulls in the whole engine API.
#include "cardengine/bot.h"
#include "cardengine/bot_runner.h"
#include "cardengine/card.h"
#include "cardengine/championship.h"
#include "cardengine/clock.h"
#include "cardengine/config.h"
#include "cardengine/deck.h"
#include "cardengine/event.h"
#include "cardengine/game_file.h"
#include "cardengine/hand.h"
#include "cardengine/protocol.h"
#include "cardengine/session_file.h"
#include "cardengine/table.h"
#include "cardengine/tournament.h"

// Version constants are generated by CMake from the project() VERSION in the
// root CMakeLists.txt (build-dir cardengine/version.h) — single-sourced,
// never hand-edited.
#include "cardengine/version.h"

#include <string>

namespace cardengine {

// Human-readable "major.minor.patch".
std::string version_string();

}  // namespace cardengine
